version: '3.3'

services:
  grocery-app:
    image: grocery-test
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - MONGODB_PORT=27017
      - MONGODB_NAME=test-grocery
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
        - '27017:27017'
    command: mongod --smallfiles --logpath=/dev/null --quiet
  redis:
    image: redis:alpine
    container_name: 'redis'