version: "3.3"

services:
  grocery-app:
    image: grocery-app
    container_name: "api"
    environment:
      - NODE_ENV=development
      - MONGODB_PORT=27017
      - MONGODB_NAME=grocery-app
      - APP_PORT=3000
    ports:
      - "3000"
      - "5858"
    volumes:
      - ./server:/server
      - ./node_modules:/node_modules
      - ./wait-for:/wait-for
    command: sh -c './wait-for mongodb:27017 && ./wait-for redis:6379 && npm start'
    depends_on:
      - seeder
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017"
    command: mongod --smallfiles --logpath=/dev/null --quiet
  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - "6379"
  seeder:
    image: seeder
    build:
      context: ./seeds
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    command: sh -c './seed-db.sh'