FROM node:8.9-alpine

WORKDIR .
ADD . .

RUN npm install

EXPOSE 3000

ENV NODE_ENV test
CMD ["npm", "run", "test"]


# Copy source code
COPY . /app

# Change working directory
WORKDIR /app

# Install dependencies
RUN npm install

# Expose API port to the outside
EXPOSE 80