version: '2.1'

services:
  grocery-app:
    image: grocery-app
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: nopm start