version: '3.3'

services:
  grocery-app:
    image: grocery-app
    build: .
    environment:
      - NODE_ENV=development
      - MONGODB_PORT=27017
      - MONGODB_NAME=grocery-app
    ports:
      - '3000:3000'
      - '5858:5858'
    volumes:
      - ./server:/server
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - '27017:27017'
    command: mongod --smallfiles --logpath=/dev/null --quiet
  redis:
    image: redis:alpine
    container_name: 'redis'
    ports:
      - '6379:6379'